// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAho0_TTg525h1IuJilwJ0orNmqh8qS9TA',
    appId: '1:861600816011:web:9b3296a0452d6080a4ed8e',
    messagingSenderId: '861600816011',
    projectId: 'ccse-mob',
    authDomain: 'ccse-mob.firebaseapp.com',
    storageBucket: 'ccse-mob.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtg42MmW_Y5Sq8875YQSNP_3UKM0hf2V8',
    appId: '1:861600816011:android:388fb5298e78158ca4ed8e',
    messagingSenderId: '861600816011',
    projectId: 'ccse-mob',
    storageBucket: 'ccse-mob.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuFzzj-YO0ORg-uyttpNHTz6hkn3yLtJw',
    appId: '1:861600816011:ios:d252afc592251e08a4ed8e',
    messagingSenderId: '861600816011',
    projectId: 'ccse-mob',
    storageBucket: 'ccse-mob.firebasestorage.app',
    iosBundleId: 'com.ccsefacil.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuFzzj-YO0ORg-uyttpNHTz6hkn3yLtJw',
    appId: '1:861600816011:ios:20ee9e1bf465fb77a4ed8e',
    messagingSenderId: '861600816011',
    projectId: 'ccse-mob',
    storageBucket: 'ccse-mob.firebasestorage.app',
    iosBundleId: 'com.ccsefacil.ctaProjetoAutonomo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAho0_TTg525h1IuJilwJ0orNmqh8qS9TA',
    appId: '1:861600816011:web:86b1b191900295a3a4ed8e',
    messagingSenderId: '861600816011',
    projectId: 'ccse-mob',
    authDomain: 'ccse-mob.firebaseapp.com',
    storageBucket: 'ccse-mob.firebasestorage.app',
  );
}
